name: DeployToGitHubPages
env:
  PUBLISH_DIR: TestBlazorClient/bin/Release/net5.0/publish/wwwroot

# Controls when the action will run
on:
  workflow_dispatch: # 网页上手动
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /TestBlazorClient/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
